version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.13.4-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  nats:
    image: nats:2.10.17-alpine3.20
    container_name: "nats"
    ports:
      - 4222:4222
